services:
  mujoco_web:
    container_name: mujoco_web
    image: node:lts
    tty: true
    entrypoint: /bin/bash
    ports:
      - 5173:5173
    volumes:
      - ./mujoco_web:/app
    working_dir: /app
