#include <cstdio>
#include <cstring>

#include "mujoco/mujoco.h"

#include <emscripten.h>
#include <emscripten/fetch.h>
#include <emscripten/val.h>

#include <model.h>
#include <simulation.h>
#include <state.h>

using namespace emscripten;

// main function
int main(int argc, char **argv) {
  std::printf("MuJoCo version: %d\n\n", mj_version());
  return 0;
}

EMSCRIPTEN_BINDINGS(mujoco_wasm) {

  // MODEL_ENUMS
  enum_<mjtDisableBit>("mjtDisableBit")
      .value("mjDSBL_CONSTRAINT", mjtDisableBit ::mjDSBL_CONSTRAINT)
      .value("mjDSBL_EQUALITY", mjtDisableBit ::mjDSBL_EQUALITY)
      .value("mjDSBL_FRICTIONLOSS", mjtDisableBit ::mjDSBL_FRICTIONLOSS)
      .value("mjDSBL_LIMIT", mjtDisableBit ::mjDSBL_LIMIT)
      .value("mjDSBL_CONTACT", mjtDisableBit ::mjDSBL_CONTACT)
      .value("mjDSBL_PASSIVE", mjtDisableBit ::mjDSBL_PASSIVE)
      .value("mjDSBL_GRAVITY", mjtDisableBit ::mjDSBL_GRAVITY)
      .value("mjDSBL_CLAMPCTRL", mjtDisableBit ::mjDSBL_CLAMPCTRL)
      .value("mjDSBL_WARMSTART", mjtDisableBit ::mjDSBL_WARMSTART)
      .value("mjDSBL_FILTERPARENT", mjtDisableBit ::mjDSBL_FILTERPARENT)
      .value("mjDSBL_ACTUATION", mjtDisableBit ::mjDSBL_ACTUATION)
      .value("mjDSBL_REFSAFE", mjtDisableBit ::mjDSBL_REFSAFE)
      .value("mjDSBL_SENSOR", mjtDisableBit ::mjDSBL_SENSOR)
      .value("mjDSBL_MIDPHASE", mjtDisableBit ::mjDSBL_MIDPHASE)
      .value("mjDSBL_EULERDAMP", mjtDisableBit ::mjDSBL_EULERDAMP)
      .value("mjDSBL_AUTORESET", mjtDisableBit ::mjDSBL_AUTORESET)
      .value("mjNDISABLE", mjtDisableBit ::mjNDISABLE);
  enum_<mjtEnableBit>("mjtEnableBit")
      .value("mjENBL_OVERRIDE", mjtEnableBit ::mjENBL_OVERRIDE)
      .value("mjENBL_ENERGY", mjtEnableBit ::mjENBL_ENERGY)
      .value("mjENBL_FWDINV", mjtEnableBit ::mjENBL_FWDINV)
      .value("mjENBL_INVDISCRETE", mjtEnableBit ::mjENBL_INVDISCRETE)
      .value("mjENBL_MULTICCD", mjtEnableBit ::mjENBL_MULTICCD)
      .value("mjENBL_ISLAND", mjtEnableBit ::mjENBL_ISLAND)
      .value("mjENBL_NATIVECCD", mjtEnableBit ::mjENBL_NATIVECCD)
      .value("mjNENABLE", mjtEnableBit ::mjNENABLE);
  enum_<mjtJoint>("mjtJoint")
      .value("mjJNT_FREE", mjtJoint ::mjJNT_FREE)
      .value("mjJNT_BALL", mjtJoint ::mjJNT_BALL)
      .value("mjJNT_SLIDE", mjtJoint ::mjJNT_SLIDE)
      .value("mjJNT_HINGE", mjtJoint ::mjJNT_HINGE);
  enum_<mjtGeom>("mjtGeom")
      .value("mjGEOM_PLANE", mjtGeom ::mjGEOM_PLANE)
      .value("mjGEOM_HFIELD", mjtGeom ::mjGEOM_HFIELD)
      .value("mjGEOM_SPHERE", mjtGeom ::mjGEOM_SPHERE)
      .value("mjGEOM_CAPSULE", mjtGeom ::mjGEOM_CAPSULE)
      .value("mjGEOM_ELLIPSOID", mjtGeom ::mjGEOM_ELLIPSOID)
      .value("mjGEOM_CYLINDER", mjtGeom ::mjGEOM_CYLINDER)
      .value("mjGEOM_BOX", mjtGeom ::mjGEOM_BOX)
      .value("mjGEOM_MESH", mjtGeom ::mjGEOM_MESH)
      .value("mjGEOM_SDF", mjtGeom ::mjGEOM_SDF)
      .value("mjNGEOMTYPES", mjtGeom ::mjNGEOMTYPES)
      .value("mjGEOM_ARROW", mjtGeom ::mjGEOM_ARROW)
      .value("mjGEOM_ARROW1", mjtGeom ::mjGEOM_ARROW1)
      .value("mjGEOM_ARROW2", mjtGeom ::mjGEOM_ARROW2)
      .value("mjGEOM_LINE", mjtGeom ::mjGEOM_LINE)
      .value("mjGEOM_LINEBOX", mjtGeom ::mjGEOM_LINEBOX)
      .value("mjGEOM_FLEX", mjtGeom ::mjGEOM_FLEX)
      .value("mjGEOM_SKIN", mjtGeom ::mjGEOM_SKIN)
      .value("mjGEOM_LABEL", mjtGeom ::mjGEOM_LABEL)
      .value("mjGEOM_TRIANGLE", mjtGeom ::mjGEOM_TRIANGLE)
      .value("mjGEOM_NONE", mjtGeom ::mjGEOM_NONE);
  enum_<mjtCamLight>("mjtCamLight")
      .value("mjCAMLIGHT_FIXED", mjtCamLight ::mjCAMLIGHT_FIXED)
      .value("mjCAMLIGHT_TRACK", mjtCamLight ::mjCAMLIGHT_TRACK)
      .value("mjCAMLIGHT_TRACKCOM", mjtCamLight ::mjCAMLIGHT_TRACKCOM)
      .value("mjCAMLIGHT_TARGETBODY", mjtCamLight ::mjCAMLIGHT_TARGETBODY)
      .value("mjCAMLIGHT_TARGETBODYCOM",
             mjtCamLight ::mjCAMLIGHT_TARGETBODYCOM);
  enum_<mjtTexture>("mjtTexture")
      .value("mjTEXTURE_2D", mjtTexture ::mjTEXTURE_2D)
      .value("mjTEXTURE_CUBE", mjtTexture ::mjTEXTURE_CUBE)
      .value("mjTEXTURE_SKYBOX", mjtTexture ::mjTEXTURE_SKYBOX);
  enum_<mjtTextureRole>("mjtTextureRole")
      .value("mjTEXROLE_USER", mjtTextureRole ::mjTEXROLE_USER)
      .value("mjTEXROLE_RGB", mjtTextureRole ::mjTEXROLE_RGB)
      .value("mjTEXROLE_OCCLUSION", mjtTextureRole ::mjTEXROLE_OCCLUSION)
      .value("mjTEXROLE_ROUGHNESS", mjtTextureRole ::mjTEXROLE_ROUGHNESS)
      .value("mjTEXROLE_METALLIC", mjtTextureRole ::mjTEXROLE_METALLIC)
      .value("mjTEXROLE_NORMAL", mjtTextureRole ::mjTEXROLE_NORMAL)
      .value("mjTEXROLE_OPACITY", mjtTextureRole ::mjTEXROLE_OPACITY)
      .value("mjTEXROLE_EMISSIVE", mjtTextureRole ::mjTEXROLE_EMISSIVE)
      .value("mjTEXROLE_RGBA", mjtTextureRole ::mjTEXROLE_RGBA)
      .value("mjTEXROLE_ORM", mjtTextureRole ::mjTEXROLE_ORM)
      .value("mjNTEXROLE", mjtTextureRole ::mjNTEXROLE);
  enum_<mjtIntegrator>("mjtIntegrator")
      .value("mjINT_EULER", mjtIntegrator ::mjINT_EULER)
      .value("mjINT_RK4", mjtIntegrator ::mjINT_RK4)
      .value("mjINT_IMPLICIT", mjtIntegrator ::mjINT_IMPLICIT)
      .value("mjINT_IMPLICITFAST", mjtIntegrator ::mjINT_IMPLICITFAST);
  enum_<mjtCone>("mjtCone")
      .value("mjCONE_PYRAMIDAL", mjtCone ::mjCONE_PYRAMIDAL)
      .value("mjCONE_ELLIPTIC", mjtCone ::mjCONE_ELLIPTIC);
  enum_<mjtJacobian>("mjtJacobian")
      .value("mjJAC_DENSE", mjtJacobian ::mjJAC_DENSE)
      .value("mjJAC_SPARSE", mjtJacobian ::mjJAC_SPARSE)
      .value("mjJAC_AUTO", mjtJacobian ::mjJAC_AUTO);
  enum_<mjtSolver>("mjtSolver")
      .value("mjSOL_PGS", mjtSolver ::mjSOL_PGS)
      .value("mjSOL_CG", mjtSolver ::mjSOL_CG)
      .value("mjSOL_NEWTON", mjtSolver ::mjSOL_NEWTON);
  enum_<mjtEq>("mjtEq")
      .value("mjEQ_CONNECT", mjtEq ::mjEQ_CONNECT)
      .value("mjEQ_WELD", mjtEq ::mjEQ_WELD)
      .value("mjEQ_JOINT", mjtEq ::mjEQ_JOINT)
      .value("mjEQ_TENDON", mjtEq ::mjEQ_TENDON)
      .value("mjEQ_FLEX", mjtEq ::mjEQ_FLEX)
      .value("mjEQ_DISTANCE", mjtEq ::mjEQ_DISTANCE);
  enum_<mjtWrap>("mjtWrap")
      .value("mjWRAP_NONE", mjtWrap ::mjWRAP_NONE)
      .value("mjWRAP_JOINT", mjtWrap ::mjWRAP_JOINT)
      .value("mjWRAP_PULLEY", mjtWrap ::mjWRAP_PULLEY)
      .value("mjWRAP_SITE", mjtWrap ::mjWRAP_SITE)
      .value("mjWRAP_SPHERE", mjtWrap ::mjWRAP_SPHERE)
      .value("mjWRAP_CYLINDER", mjtWrap ::mjWRAP_CYLINDER);
  enum_<mjtTrn>("mjtTrn")
      .value("mjTRN_JOINT", mjtTrn ::mjTRN_JOINT)
      .value("mjTRN_JOINTINPARENT", mjtTrn ::mjTRN_JOINTINPARENT)
      .value("mjTRN_SLIDERCRANK", mjtTrn ::mjTRN_SLIDERCRANK)
      .value("mjTRN_TENDON", mjtTrn ::mjTRN_TENDON)
      .value("mjTRN_SITE", mjtTrn ::mjTRN_SITE)
      .value("mjTRN_BODY", mjtTrn ::mjTRN_BODY)
      .value("mjTRN_UNDEFINED", mjtTrn ::mjTRN_UNDEFINED);
  enum_<mjtDyn>("mjtDyn")
      .value("mjDYN_NONE", mjtDyn ::mjDYN_NONE)
      .value("mjDYN_INTEGRATOR", mjtDyn ::mjDYN_INTEGRATOR)
      .value("mjDYN_FILTER", mjtDyn ::mjDYN_FILTER)
      .value("mjDYN_FILTER", mjtDyn ::mjDYN_FILTER)
      .value("mjDYN_FILTEREXACT", mjtDyn ::mjDYN_FILTEREXACT)
      .value("mjDYN_MUSCLE", mjtDyn ::mjDYN_MUSCLE)
      .value("mjDYN_USER", mjtDyn ::mjDYN_USER);
  enum_<mjtGain>("mjtGain")
      .value("mjGAIN_FIXED", mjtGain ::mjGAIN_FIXED)
      .value("mjGAIN_AFFINE", mjtGain ::mjGAIN_AFFINE)
      .value("mjGAIN_MUSCLE", mjtGain ::mjGAIN_MUSCLE)
      .value("mjGAIN_USER", mjtGain ::mjGAIN_USER);
  enum_<mjtBias>("mjtBias")
      .value("mjBIAS_NONE", mjtBias ::mjBIAS_NONE)
      .value("mjBIAS_AFFINE", mjtBias ::mjBIAS_AFFINE)
      .value("mjBIAS_MUSCLE", mjtBias ::mjBIAS_MUSCLE)
      .value("mjBIAS_USER", mjtBias ::mjBIAS_USER);
  enum_<mjtObj>("mjtObj")
      .value("mjOBJ_UNKNOWN", mjtObj ::mjOBJ_UNKNOWN)
      .value("mjOBJ_BODY", mjtObj ::mjOBJ_BODY)
      .value("mjOBJ_XBODY", mjtObj ::mjOBJ_XBODY)
      .value("mjOBJ_JOINT", mjtObj ::mjOBJ_JOINT)
      .value("mjOBJ_DOF", mjtObj ::mjOBJ_DOF)
      .value("mjOBJ_GEOM", mjtObj ::mjOBJ_GEOM)
      .value("mjOBJ_SITE", mjtObj ::mjOBJ_SITE)
      .value("mjOBJ_CAMERA", mjtObj ::mjOBJ_CAMERA)
      .value("mjOBJ_LIGHT", mjtObj ::mjOBJ_LIGHT)
      .value("mjOBJ_MESH", mjtObj ::mjOBJ_MESH)
      .value("mjOBJ_SKIN", mjtObj ::mjOBJ_SKIN)
      .value("mjOBJ_HFIELD", mjtObj ::mjOBJ_HFIELD)
      .value("mjOBJ_TEXTURE", mjtObj ::mjOBJ_TEXTURE)
      .value("mjOBJ_MATERIAL", mjtObj ::mjOBJ_MATERIAL)
      .value("mjOBJ_PAIR", mjtObj ::mjOBJ_PAIR)
      .value("mjOBJ_EXCLUDE", mjtObj ::mjOBJ_EXCLUDE)
      .value("mjOBJ_EQUALITY", mjtObj ::mjOBJ_EQUALITY)
      .value("mjOBJ_TENDON", mjtObj ::mjOBJ_TENDON)
      .value("mjOBJ_ACTUATOR", mjtObj ::mjOBJ_ACTUATOR)
      .value("mjOBJ_SENSOR", mjtObj ::mjOBJ_SENSOR)
      .value("mjOBJ_NUMERIC", mjtObj ::mjOBJ_NUMERIC)
      .value("mjOBJ_TEXT", mjtObj ::mjOBJ_TEXT)
      .value("mjOBJ_TUPLE", mjtObj ::mjOBJ_TUPLE)
      .value("mjOBJ_KEY", mjtObj ::mjOBJ_KEY)
      .value("mjOBJ_PLUGIN", mjtObj ::mjOBJ_PLUGIN);
  enum_<mjtConstraint>("mjtConstraint")
      .value("mjCNSTR_EQUALITY", mjtConstraint ::mjCNSTR_EQUALITY)
      .value("mjCNSTR_FRICTION_DOF", mjtConstraint ::mjCNSTR_FRICTION_DOF)
      .value("mjCNSTR_FRICTION_TENDON", mjtConstraint ::mjCNSTR_FRICTION_TENDON)
      .value("mjCNSTR_LIMIT_JOINT", mjtConstraint ::mjCNSTR_LIMIT_JOINT)
      .value("mjCNSTR_LIMIT_TENDON", mjtConstraint ::mjCNSTR_LIMIT_TENDON)
      .value("mjCNSTR_CONTACT_FRICTIONLESS",
             mjtConstraint ::mjCNSTR_CONTACT_FRICTIONLESS)
      .value("mjCNSTR_CONTACT_PYRAMIDAL",
             mjtConstraint ::mjCNSTR_CONTACT_PYRAMIDAL)
      .value("mjCNSTR_CONTACT_ELLIPTIC",
             mjtConstraint ::mjCNSTR_CONTACT_ELLIPTIC);
  enum_<mjtConstraintState>("mjtConstraintState")
      .value("mjCNSTRSTATE_SATISFIED",
             mjtConstraintState ::mjCNSTRSTATE_SATISFIED)
      .value("mjCNSTRSTATE_QUADRATIC",
             mjtConstraintState ::mjCNSTRSTATE_QUADRATIC)
      .value("mjCNSTRSTATE_LINEARNEG",
             mjtConstraintState ::mjCNSTRSTATE_LINEARNEG)
      .value("mjCNSTRSTATE_LINEARPOS",
             mjtConstraintState ::mjCNSTRSTATE_LINEARPOS)
      .value("mjCNSTRSTATE_CONE", mjtConstraintState ::mjCNSTRSTATE_CONE);
  enum_<mjtSensor>("mjtSensor")
      .value("mjSENS_TOUCH", mjtSensor ::mjSENS_TOUCH)
      .value("mjSENS_ACCELEROMETER", mjtSensor ::mjSENS_ACCELEROMETER)
      .value("mjSENS_VELOCIMETER", mjtSensor ::mjSENS_VELOCIMETER)
      .value("mjSENS_GYRO", mjtSensor ::mjSENS_GYRO)
      .value("mjSENS_FORCE", mjtSensor ::mjSENS_FORCE)
      .value("mjSENS_TORQUE", mjtSensor ::mjSENS_TORQUE)
      .value("mjSENS_MAGNETOMETER", mjtSensor ::mjSENS_MAGNETOMETER)
      .value("mjSENS_RANGEFINDER", mjtSensor ::mjSENS_RANGEFINDER)
      .value("mjSENS_CAMPROJECTION", mjtSensor ::mjSENS_CAMPROJECTION)
      .value("mjSENS_JOINTPOS", mjtSensor ::mjSENS_JOINTPOS)
      .value("mjSENS_JOINTVEL", mjtSensor ::mjSENS_JOINTVEL)
      .value("mjSENS_TENDONPOS", mjtSensor ::mjSENS_TENDONPOS)
      .value("mjSENS_TENDONVEL", mjtSensor ::mjSENS_TENDONVEL)
      .value("mjSENS_ACTUATORPOS", mjtSensor ::mjSENS_ACTUATORPOS)
      .value("mjSENS_ACTUATORVEL", mjtSensor ::mjSENS_ACTUATORVEL)
      .value("mjSENS_ACTUATORFRC", mjtSensor ::mjSENS_ACTUATORFRC)
      .value("mjSENS_BALLQUAT", mjtSensor ::mjSENS_BALLQUAT)
      .value("mjSENS_BALLANGVEL", mjtSensor ::mjSENS_BALLANGVEL)
      .value("mjSENS_JOINTLIMITPOS", mjtSensor ::mjSENS_JOINTLIMITPOS)
      .value("mjSENS_JOINTLIMITVEL", mjtSensor ::mjSENS_JOINTLIMITVEL)
      .value("mjSENS_JOINTLIMITFRC", mjtSensor ::mjSENS_JOINTLIMITFRC)
      .value("mjSENS_TENDONLIMITPOS", mjtSensor ::mjSENS_TENDONLIMITPOS)
      .value("mjSENS_TENDONLIMITVEL", mjtSensor ::mjSENS_TENDONLIMITVEL)
      .value("mjSENS_TENDONLIMITFRC", mjtSensor ::mjSENS_TENDONLIMITFRC)
      .value("mjSENS_FRAMEPOS", mjtSensor ::mjSENS_FRAMEPOS)
      .value("mjSENS_FRAMEQUAT", mjtSensor ::mjSENS_FRAMEQUAT)
      .value("mjSENS_FRAMEXAXIS", mjtSensor ::mjSENS_FRAMEXAXIS)
      .value("mjSENS_FRAMEYAXIS", mjtSensor ::mjSENS_FRAMEYAXIS)
      .value("mjSENS_FRAMEZAXIS", mjtSensor ::mjSENS_FRAMEZAXIS)
      .value("mjSENS_FRAMELINVEL", mjtSensor ::mjSENS_FRAMELINVEL)
      .value("mjSENS_FRAMEANGVEL", mjtSensor ::mjSENS_FRAMEANGVEL)
      .value("mjSENS_FRAMELINACC", mjtSensor ::mjSENS_FRAMELINACC)
      .value("mjSENS_FRAMEANGACC", mjtSensor ::mjSENS_FRAMEANGACC)
      .value("mjSENS_SUBTREECOM", mjtSensor ::mjSENS_SUBTREECOM)
      .value("mjSENS_SUBTREELINVEL", mjtSensor ::mjSENS_SUBTREELINVEL)
      .value("mjSENS_SUBTREEANGMOM", mjtSensor ::mjSENS_SUBTREEANGMOM)
      .value("mjSENS_GEOMDIST", mjtSensor ::mjSENS_GEOMDIST)
      .value("mjSENS_GEOMNORMAL", mjtSensor ::mjSENS_GEOMNORMAL)
      .value("mjSENS_GEOMFROMTO", mjtSensor ::mjSENS_GEOMFROMTO)
      .value("mjSENS_CLOCK", mjtSensor ::mjSENS_CLOCK)
      .value("mjSENS_PLUGIN", mjtSensor ::mjSENS_PLUGIN)
      .value("mjSENS_USER", mjtSensor ::mjSENS_USER);
  enum_<mjtStage>("mjtStage")
      .value("mjSTAGE_NONE", mjtStage ::mjSTAGE_NONE)
      .value("mjSTAGE_POS", mjtStage ::mjSTAGE_POS)
      .value("mjSTAGE_VEL", mjtStage ::mjSTAGE_VEL)
      .value("mjSTAGE_ACC", mjtStage ::mjSTAGE_ACC);
  enum_<mjtDataType>("mjtDataType")
      .value("mjDATATYPE_REAL", mjtDataType ::mjDATATYPE_REAL)
      .value("mjDATATYPE_POSITIVE", mjtDataType ::mjDATATYPE_POSITIVE)
      .value("mjDATATYPE_AXIS", mjtDataType ::mjDATATYPE_AXIS)
      .value("mjDATATYPE_QUATERNION", mjtDataType ::mjDATATYPE_QUATERNION);
  enum_<mjtSameFrame>("mjtSameFrame")
      .value("mjSAMEFRAME_NONE", mjtSameFrame ::mjSAMEFRAME_NONE)
      .value("mjSAMEFRAME_BODY", mjtSameFrame ::mjSAMEFRAME_BODY)
      .value("mjSAMEFRAME_INERTIA", mjtSameFrame ::mjSAMEFRAME_INERTIA)
      .value("mjSAMEFRAME_BODYROT", mjtSameFrame ::mjSAMEFRAME_BODYROT)
      .value("mjSAMEFRAME_INERTIAROT", mjtSameFrame ::mjSAMEFRAME_INERTIAROT);
  enum_<mjtLRMode>("mjtLRMode")
      .value("mjLRMODE_NONE", mjtLRMode ::mjLRMODE_NONE)
      .value("mjLRMODE_MUSCLE", mjtLRMode ::mjLRMODE_MUSCLE)
      .value("mjLRMODE_MUSCLEUSER", mjtLRMode ::mjLRMODE_MUSCLEUSER)
      .value("mjLRMODE_ALL", mjtLRMode ::mjLRMODE_ALL);

  enum_<mjtFlexSelf>("mjtFlexSelf")
      .value("mjFLEXSELF_NONE", mjtFlexSelf ::mjFLEXSELF_NONE)
      .value("mjFLEXSELF_NARROW", mjtFlexSelf ::mjFLEXSELF_NARROW)
      .value("mjFLEXSELF_BVH", mjtFlexSelf ::mjFLEXSELF_BVH)
      .value("mjFLEXSELF_SAP", mjtFlexSelf ::mjFLEXSELF_SAP)
      .value("mjFLEXSELF_AUTO", mjtFlexSelf ::mjFLEXSELF_AUTO);

  value_object<mjLROpt>("mjLROpt")
      .field("mode", &mjLROpt::mode)
      .field("useexisting", &mjLROpt::useexisting)
      .field("uselimit", &mjLROpt::uselimit)
      .field("accel", &mjLROpt::accel)
      .field("maxforce", &mjLROpt::maxforce)
      .field("timeconst", &mjLROpt::timeconst)
      .field("timestep", &mjLROpt::timestep)
      .field("inttotal", &mjLROpt::inttotal)
      .field("interval", &mjLROpt::interval)
      .field("tolrange", &mjLROpt::tolrange);

  value_object<mjOption>("mjOption")
      .field("timestep", &mjOption::timestep)
      .field("apirate", &mjOption::apirate)
      .field("impratio", &mjOption::impratio)
      .field("tolerance", &mjOption::tolerance)
      .field("ls_tolerance", &mjOption::ls_tolerance)
      .field("noslip_tolerance", &mjOption::noslip_tolerance)
      .field("ccd_tolerance", &mjOption::ccd_tolerance)
      //.field("gravity" , &mjOption::gravity)
      //.field("wind" , &mjOption::wind)
      //.field("magnetic" , &mjOption::magnetic)
      .field("density", &mjOption::density)
      .field("viscosity", &mjOption::viscosity)
      .field("o_margin", &mjOption::o_margin)
      //.field("o_solref" , &mjOption::o_solref)
      //.field("o_solimp" , &mjOption::o_solimp)
      //.field("o_friction" , &mjOption::o_friction)
      .field("integrator", &mjOption::integrator)
      .field("cone", &mjOption::cone)
      .field("jacobian", &mjOption::jacobian)
      .field("solver", &mjOption::solver)
      .field("iterations", &mjOption::iterations)
      .field("iterations", &mjOption::iterations)
      .field("ls_iterations", &mjOption::ls_iterations)
      .field("noslip_iterations", &mjOption::noslip_iterations)
      .field("ccd_iterations", &mjOption::ccd_iterations)
      .field("disableflags", &mjOption::disableflags)
      .field("enableflags", &mjOption::enableflags)
      .field("disableactuator", &mjOption::disableactuator)
      .field("sdf_initpoints", &mjOption::sdf_initpoints)
      .field("sdf_iterations", &mjOption::sdf_iterations);

  class_<Model>("Model")
      .constructor<>(&Model::load_from_xml)
      .class_function("load_from_xml", &Model::load_from_xml)
      .class_function("load_from_mjb", &Model::load_from_mjb)
      .function("ptr", &Model::ptr, allow_raw_pointers())
      .function("free", &Model::free)
      .function("getVal", &Model::getVal)
      .function("getOptions", &Model::getOptions)

      // MJMODEL_BINDINGS

      // sizes needed at mjModel construction
      .property("nq", &Model::nq)
      .property("nv", &Model::nv)
      .property("nu", &Model::nu)
      .property("na", &Model::na)
      .property("nbody", &Model::nbody)
      .property("nbvhstatic", &Model::nbvhstatic)
      .property("nbvhdynamic", &Model::nbvhdynamic)
      .property("njnt", &Model::njnt)
      .property("ngeom", &Model::ngeom)
      .property("nsite", &Model::nsite)
      .property("ncam", &Model::ncam)
      .property("nlight", &Model::nlight)
      .property("nflex", &Model::nflex)
      .property("nflexvert", &Model::nflexvert)
      .property("nflexedge", &Model::nflexedge)
      .property("nflexelem", &Model::nflexelem)
      .property("nflexelemdata", &Model::nflexelemdata)
      .property("nflexelemedge", &Model::nflexelemedge)
      .property("nflexshelldata", &Model::nflexshelldata)
      .property("nflexevpair", &Model::nflexevpair)
      .property("nflextexcoord", &Model::nflextexcoord)
      .property("nmesh", &Model::nmesh)
      .property("nmeshvert", &Model::nmeshvert)
      .property("nmeshnormal", &Model::nmeshnormal)
      .property("nmeshtexcoord", &Model::nmeshtexcoord)
      .property("nmeshface", &Model::nmeshface)
      .property("nmeshgraph", &Model::nmeshgraph)
      .property("nskin", &Model::nskin)
      .property("nskinvert", &Model::nskinvert)
      .property("nskintexvert", &Model::nskintexvert)
      .property("nskinface", &Model::nskinface)
      .property("nskinbone", &Model::nskinbone)
      .property("nskinbonevert", &Model::nskinbonevert)
      .property("nhfield", &Model::nhfield)
      .property("nhfielddata", &Model::nhfielddata)
      .property("ntex", &Model::ntex)
      .property("ntexdata", &Model::ntexdata)
      .property("nmat", &Model::nmat)
      .property("npair", &Model::npair)
      .property("nexclude", &Model::nexclude)
      .property("neq", &Model::neq)
      .property("ntendon", &Model::ntendon)
      .property("nwrap", &Model::nwrap)
      .property("nsensor", &Model::nsensor)
      .property("nnumeric", &Model::nnumeric)
      .property("nnumericdata", &Model::nnumericdata)
      .property("ntext", &Model::ntext)
      .property("ntextdata", &Model::ntextdata)
      .property("ntuple", &Model::ntuple)
      .property("ntupledata", &Model::ntupledata)
      .property("nkey", &Model::nkey)
      .property("nmocap", &Model::nmocap)
      .property("nplugin", &Model::nplugin)
      .property("npluginattr", &Model::npluginattr)
      .property("nuser_body", &Model::nuser_body)
      .property("nuser_jnt", &Model::nuser_jnt)
      .property("nuser_geom", &Model::nuser_geom)
      .property("nuser_site", &Model::nuser_site)
      .property("nuser_cam", &Model::nuser_cam)
      .property("nuser_tendon", &Model::nuser_tendon)
      .property("nuser_actuator", &Model::nuser_actuator)
      .property("nuser_sensor", &Model::nuser_sensor)
      .property("nnames", &Model::nnames)
      .property("npaths", &Model::npaths)

      // sizes set after mjModel construction (only affect mjData)
      .property("nM", &Model::nM)
      .property("nB", &Model::nB)
      .property("nC", &Model::nC)
      .property("nD", &Model::nD)
      .property("ntree", &Model::ntree)
      .property("ngravcomp", &Model::ngravcomp)
      .property("nemax", &Model::nemax)
      .property("njmax", &Model::njmax)
      .property("nconmax", &Model::nconmax)
      .property("nuserdata", &Model::nuserdata)
      .property("nsensordata", &Model::nsensordata)
      .property("npluginstate", &Model::npluginstate)
      .property("narena", &Model::narena)
      .property("nbuffer", &Model::nbuffer)

      // default generalized coordinates
      .property("qpos0", &Model::qpos0)
      .property("qpos_spring", &Model::qpos_spring)

      // bodies
      .property("body_parentid", &Model::body_parentid)
      .property("body_rootid", &Model::body_rootid)
      .property("body_weldid", &Model::body_weldid)
      .property("body_mocapid", &Model::body_mocapid)
      .property("body_jntnum", &Model::body_jntnum)
      .property("body_jntadr", &Model::body_jntadr)
      .property("body_dofnum", &Model::body_dofnum)
      .property("body_dofadr", &Model::body_dofadr)
      .property("body_geomnum", &Model::body_geomnum)
      .property("body_geomadr", &Model::body_geomadr)
      .property("body_simple", &Model::body_simple)
      .property("body_sameframe", &Model::body_sameframe)
      .property("body_pos", &Model::body_pos)
      .property("body_quat", &Model::body_quat)
      .property("body_ipos", &Model::body_ipos)
      .property("body_iquat", &Model::body_iquat)
      .property("body_mass", &Model::body_mass)
      .property("body_subtreemass", &Model::body_subtreemass)
      .property("body_inertia", &Model::body_inertia)
      .property("body_invweight0", &Model::body_invweight0)
      .property("body_gravcomp", &Model::body_gravcomp)
      .property("body_user", &Model::body_user)
      .property("body_plugin", &Model::body_plugin)
      .property("body_contype", &Model::body_contype)
      .property("body_conaffinity", &Model::body_conaffinity)
      .property("body_bvhadr", &Model::body_bvhadr)
      .property("body_bvhnum", &Model::body_bvhnum)

      // bounding volume hierarchy
      .property("bvh_depth", &Model::bvh_depth)
      .property("bvh_child", &Model::bvh_child)
      .property("bvh_nodeid", &Model::bvh_nodeid)
      .property("bvh_aabb", &Model::bvh_aabb)

      // joints
      .property("jnt_type", &Model::jnt_type)
      .property("jnt_qposadr", &Model::jnt_qposadr)
      .property("jnt_dofadr", &Model::jnt_dofadr)
      .property("jnt_bodyid", &Model::jnt_bodyid)
      .property("jnt_group", &Model::jnt_group)
      .property("jnt_limited", &Model::jnt_limited)
      .property("jnt_actfrclimited", &Model::jnt_actfrclimited)
      .property("jnt_actgravcomp", &Model::jnt_actgravcomp)
      .property("jnt_solref", &Model::jnt_solref)
      .property("jnt_solimp", &Model::jnt_solimp)
      .property("jnt_pos", &Model::jnt_pos)
      .property("jnt_axis", &Model::jnt_axis)
      .property("jnt_stiffness", &Model::jnt_stiffness)
      .property("jnt_range", &Model::jnt_range)
      .property("jnt_actfrcrange", &Model::jnt_actfrcrange)
      .property("jnt_margin", &Model::jnt_margin)
      .property("jnt_user", &Model::jnt_user)

      // dofs
      .property("dof_bodyid", &Model::dof_bodyid)
      .property("dof_jntid", &Model::dof_jntid)
      .property("dof_parentid", &Model::dof_parentid)
      .property("dof_treeid", &Model::dof_treeid)
      .property("dof_Madr", &Model::dof_Madr)
      .property("dof_simplenum", &Model::dof_simplenum)
      .property("dof_solref", &Model::dof_solref)
      .property("dof_solimp", &Model::dof_solimp)
      .property("dof_frictionloss", &Model::dof_frictionloss)
      .property("dof_armature", &Model::dof_armature)
      .property("dof_damping", &Model::dof_damping)
      .property("dof_invweight0", &Model::dof_invweight0)
      .property("dof_M0", &Model::dof_M0)

      // geoms
      .property("geom_type", &Model::geom_type)
      .property("geom_contype", &Model::geom_contype)
      .property("geom_conaffinity", &Model::geom_conaffinity)
      .property("geom_condim", &Model::geom_condim)
      .property("geom_bodyid", &Model::geom_bodyid)
      .property("geom_dataid", &Model::geom_dataid)
      .property("geom_matid", &Model::geom_matid)
      .property("geom_group", &Model::geom_group)
      .property("geom_priority", &Model::geom_priority)
      .property("geom_sameframe", &Model::geom_sameframe)
      .property("geom_solmix", &Model::geom_solmix)
      .property("geom_solref", &Model::geom_solref)
      .property("geom_solimp", &Model::geom_solimp)
      .property("geom_size", &Model::geom_size)
      .property("geom_aabb", &Model::geom_aabb)
      .property("geom_rbound", &Model::geom_rbound)
      .property("geom_pos", &Model::geom_pos)
      .property("geom_quat", &Model::geom_quat)
      .property("geom_friction", &Model::geom_friction)
      .property("geom_margin", &Model::geom_margin)
      .property("geom_gap", &Model::geom_gap)
      .property("geom_fluid", &Model::geom_fluid)
      .property("geom_user", &Model::geom_user)
      .property("geom_rgba", &Model::geom_rgba)

      // sites
      .property("site_type", &Model::site_type)
      .property("site_bodyid", &Model::site_bodyid)
      .property("site_matid", &Model::site_matid)
      .property("site_group", &Model::site_group)
      .property("site_sameframe", &Model::site_sameframe)
      .property("site_size", &Model::site_size)
      .property("site_pos", &Model::site_pos)
      .property("site_quat", &Model::site_quat)
      .property("site_user", &Model::site_user)
      .property("site_rgba", &Model::site_rgba)

      // cameras
      .property("cam_mode", &Model::cam_mode)
      .property("cam_bodyid", &Model::cam_bodyid)
      .property("cam_targetbodyid", &Model::cam_targetbodyid)
      .property("cam_pos", &Model::cam_pos)
      .property("cam_quat", &Model::cam_quat)
      .property("cam_poscom0", &Model::cam_poscom0)
      .property("cam_pos0", &Model::cam_pos0)
      .property("cam_mat0", &Model::cam_mat0)
      .property("cam_orthographic", &Model::cam_orthographic)
      .property("cam_fovy", &Model::cam_fovy)
      .property("cam_ipd", &Model::cam_ipd)
      .property("cam_resolution", &Model::cam_resolution)
      .property("cam_sensorsize", &Model::cam_sensorsize)
      .property("cam_intrinsic", &Model::cam_intrinsic)
      .property("cam_user", &Model::cam_user)

      // lights
      .property("light_mode", &Model::light_mode)
      .property("light_bodyid", &Model::light_bodyid)
      .property("light_targetbodyid", &Model::light_targetbodyid)
      .property("light_directional", &Model::light_directional)
      .property("light_castshadow", &Model::light_castshadow)
      .property("light_active", &Model::light_active)
      .property("light_pos", &Model::light_pos)
      .property("light_dir", &Model::light_dir)
      .property("light_poscom0", &Model::light_poscom0)
      .property("light_pos0", &Model::light_pos0)
      .property("light_dir0", &Model::light_dir0)
      .property("light_attenuation", &Model::light_attenuation)
      .property("light_cutoff", &Model::light_cutoff)
      .property("light_exponent", &Model::light_exponent)
      .property("light_ambient", &Model::light_ambient)
      .property("light_diffuse", &Model::light_diffuse)
      .property("light_specular", &Model::light_specular)

      // flexes: contact properties
      .property("flex_contype", &Model::flex_contype)
      .property("flex_conaffinity", &Model::flex_conaffinity)
      .property("flex_condim", &Model::flex_condim)
      .property("flex_priority", &Model::flex_priority)
      .property("flex_solmix", &Model::flex_solmix)
      .property("flex_solref", &Model::flex_solref)
      .property("flex_solimp", &Model::flex_solimp)
      .property("flex_friction", &Model::flex_friction)
      .property("flex_margin", &Model::flex_margin)
      .property("flex_gap", &Model::flex_gap)
      .property("flex_internal", &Model::flex_internal)
      .property("flex_selfcollide", &Model::flex_selfcollide)
      .property("flex_activelayers", &Model::flex_activelayers)

      // flexes: other properties
      .property("flex_dim", &Model::flex_dim)
      .property("flex_matid", &Model::flex_matid)
      .property("flex_group", &Model::flex_group)
      .property("flex_vertadr", &Model::flex_vertadr)
      .property("flex_vertnum", &Model::flex_vertnum)
      .property("flex_edgeadr", &Model::flex_edgeadr)
      .property("flex_edgenum", &Model::flex_edgenum)
      .property("flex_elemadr", &Model::flex_elemadr)
      .property("flex_elemnum", &Model::flex_elemnum)
      .property("flex_elemdataadr", &Model::flex_elemdataadr)
      .property("flex_elemedgeadr", &Model::flex_elemedgeadr)
      .property("flex_shellnum", &Model::flex_shellnum)
      .property("flex_shelldataadr", &Model::flex_shelldataadr)
      .property("flex_evpairadr", &Model::flex_evpairadr)
      .property("flex_evpairnum", &Model::flex_evpairnum)
      .property("flex_texcoordadr", &Model::flex_texcoordadr)
      .property("flex_vertbodyid", &Model::flex_vertbodyid)
      .property("flex_edge", &Model::flex_edge)
      .property("flex_elem", &Model::flex_elem)
      .property("flex_elemedge", &Model::flex_elemedge)
      .property("flex_elemlayer", &Model::flex_elemlayer)
      .property("flex_shell", &Model::flex_shell)
      .property("flex_evpair", &Model::flex_evpair)
      .property("flex_vert", &Model::flex_vert)
      .property("flex_xvert0", &Model::flex_xvert0)
      .property("flexedge_length0", &Model::flexedge_length0)
      .property("flexedge_invweight0", &Model::flexedge_invweight0)
      .property("flex_radius", &Model::flex_radius)
      .property("flex_stiffness", &Model::flex_stiffness)
      .property("flex_damping", &Model::flex_damping)
      .property("flex_edgestiffness", &Model::flex_edgestiffness)
      .property("flex_edgedamping", &Model::flex_edgedamping)
      .property("flex_edgeequality", &Model::flex_edgeequality)
      .property("flex_rigid", &Model::flex_rigid)
      .property("flexedge_rigid", &Model::flexedge_rigid)
      .property("flex_centered", &Model::flex_centered)
      .property("flex_flatskin", &Model::flex_flatskin)
      .property("flex_bvhadr", &Model::flex_bvhadr)
      .property("flex_bvhnum", &Model::flex_bvhnum)
      .property("flex_rgba", &Model::flex_rgba)
      .property("flex_texcoord", &Model::flex_texcoord)

      // meshes
      .property("mesh_vertadr", &Model::mesh_vertadr)
      .property("mesh_vertnum", &Model::mesh_vertnum)
      .property("mesh_faceadr", &Model::mesh_faceadr)
      .property("mesh_facenum", &Model::mesh_facenum)
      .property("mesh_bvhadr", &Model::mesh_bvhadr)
      .property("mesh_bvhnum", &Model::mesh_bvhnum)
      .property("mesh_normaladr", &Model::mesh_normaladr)
      .property("mesh_normalnum", &Model::mesh_normalnum)
      .property("mesh_texcoordadr", &Model::mesh_texcoordadr)
      .property("mesh_texcoordnum", &Model::mesh_texcoordnum)
      .property("mesh_graphadr", &Model::mesh_graphadr)
      .property("mesh_vert", &Model::mesh_vert)
      .property("mesh_normal", &Model::mesh_normal)
      .property("mesh_texcoord", &Model::mesh_texcoord)
      .property("mesh_face", &Model::mesh_face)
      .property("mesh_facenormal", &Model::mesh_facenormal)
      .property("mesh_facetexcoord", &Model::mesh_facetexcoord)
      .property("mesh_graph", &Model::mesh_graph)
      .property("mesh_scale", &Model::mesh_scale)
      .property("mesh_pos", &Model::mesh_pos)
      .property("mesh_quat", &Model::mesh_quat)
      .property(" mesh_pathadr", &Model::mesh_pathadr)

      // skins
      .property("skin_matid", &Model::skin_matid)
      .property("skin_group", &Model::skin_group)
      .property("skin_rgba", &Model::skin_rgba)
      .property("skin_inflate", &Model::skin_inflate)
      .property("skin_vertadr", &Model::skin_vertadr)
      .property("skin_vertnum", &Model::skin_vertnum)
      .property("skin_texcoordadr", &Model::skin_texcoordadr)
      .property("skin_faceadr", &Model::skin_faceadr)
      .property("skin_facenum", &Model::skin_facenum)
      .property("skin_boneadr", &Model::skin_boneadr)
      .property("skin_bonenum", &Model::skin_bonenum)
      .property("skin_vert", &Model::skin_vert)
      .property("skin_texcoord", &Model::skin_texcoord)
      .property("skin_face", &Model::skin_face)
      .property("skin_bonevertadr", &Model::skin_bonevertadr)
      .property("skin_bonevertnum", &Model::skin_bonevertnum)
      .property("skin_bonebindpos", &Model::skin_bonebindpos)
      .property("skin_bonebindquat", &Model::skin_bonebindquat)
      .property("skin_bonebodyid", &Model::skin_bonebodyid)
      .property("skin_bonevertid", &Model::skin_bonevertid)
      .property("skin_bonevertweight", &Model::skin_bonevertweight)
      .property("skin_pathadr", &Model::skin_pathadr)

      // height fields
      .property("hfield_size", &Model::hfield_size)
      .property("hfield_nrow", &Model::hfield_nrow)
      .property("hfield_ncol", &Model::hfield_ncol)
      .property("hfield_adr", &Model::hfield_adr)
      .property("hfield_data", &Model::hfield_data)
      .property("hfield_pathadr", &Model::hfield_pathadr)

      // textures
      .property("tex_type", &Model::tex_type)
      .property("tex_height", &Model::tex_height)
      .property("tex_width", &Model::tex_width)
      .property("tex_nchannel", &Model::tex_nchannel)
      .property("tex_adr", &Model::tex_adr)
      .property("tex_data", &Model::tex_data)
      .property("tex_pathadr", &Model::tex_pathadr)

      // materials
      .property("mat_texid", &Model::mat_texid)
      .property("mat_texuniform", &Model::mat_texuniform)
      .property("mat_texrepeat", &Model::mat_texrepeat)
      .property("mat_emission", &Model::mat_emission)
      .property("mat_specular", &Model::mat_specular)
      .property("mat_shininess", &Model::mat_shininess)
      .property("mat_reflectance", &Model::mat_reflectance)
      .property("mat_metallic", &Model::mat_metallic)
      .property("mat_roughness", &Model::mat_roughness)
      .property("mat_rgba", &Model::mat_rgba)

      // predefined geom pairs for collision detection; has precedence over
      // exclude
      .property("pair_dim", &Model::pair_dim)
      .property("pair_geom1", &Model::pair_geom1)
      .property("pair_geom2", &Model::pair_geom2)
      .property("pair_signature", &Model::pair_signature)
      .property("pair_solref", &Model::pair_solref)
      .property("pair_solreffriction", &Model::pair_solreffriction)
      .property("pair_solimp", &Model::pair_solimp)
      .property("pair_margin", &Model::pair_margin)
      .property("pair_gap", &Model::pair_gap)
      .property("pair_friction", &Model::pair_friction)

      // excluded body pairs for collision detection
      .property("exclude_signature", &Model::exclude_signature)

      // equality constraints
      .property("eq_type", &Model::eq_type)
      .property("eq_obj1id", &Model::eq_obj1id)
      .property("eq_obj2id", &Model::eq_obj2id)
      .property("eq_active0", &Model::eq_active0)
      .property("eq_solref", &Model::eq_solref)
      .property("eq_solimp", &Model::eq_solimp)
      .property("eq_data", &Model::eq_data)

      // tendons
      .property("tendon_adr", &Model::tendon_adr)
      .property("tendon_num", &Model::tendon_num)
      .property("tendon_matid", &Model::tendon_matid)
      .property("tendon_group", &Model::tendon_group)
      .property("tendon_limited", &Model::tendon_limited)
      .property("tendon_width", &Model::tendon_width)
      .property("tendon_solref_lim", &Model::tendon_solref_lim)
      .property("tendon_solimp_lim", &Model::tendon_solimp_lim)
      .property("tendon_solref_fri", &Model::tendon_solref_fri)
      .property("tendon_solimp_fri", &Model::tendon_solimp_fri)
      .property("tendon_range", &Model::tendon_range)
      .property("tendon_margin", &Model::tendon_margin)
      .property("tendon_stiffness", &Model::tendon_stiffness)
      .property("tendon_damping", &Model::tendon_damping)
      .property("tendon_frictionloss", &Model::tendon_frictionloss)
      .property("tendon_lengthspring", &Model::tendon_lengthspring)
      .property("tendon_length0", &Model::tendon_length0)
      .property("tendon_invweight0", &Model::tendon_invweight0)
      .property("tendon_user", &Model::tendon_user)
      .property("tendon_rgba", &Model::tendon_rgba)

      // list of all wrap objects in tendon paths
      .property("wrap_type", &Model::wrap_type)
      .property("wrap_objid", &Model::wrap_objid)
      .property("wrap_prm", &Model::wrap_prm)

      // actuators
      .property("actuator_trntype", &Model::actuator_trntype)
      .property("actuator_dyntype", &Model::actuator_dyntype)
      .property("actuator_gaintype", &Model::actuator_gaintype)
      .property("actuator_biastype", &Model::actuator_biastype)
      .property("actuator_trnid", &Model::actuator_trnid)
      .property("actuator_actadr", &Model::actuator_actadr)
      .property("actuator_actnum", &Model::actuator_actnum)
      .property("actuator_group", &Model::actuator_group)
      .property("actuator_ctrllimited", &Model::actuator_ctrllimited)
      .property("actuator_forcelimited", &Model::actuator_forcelimited)
      .property("actuator_actlimited", &Model::actuator_actlimited)
      .property("actuator_dynprm", &Model::actuator_dynprm)
      .property("actuator_gainprm", &Model::actuator_gainprm)
      .property("actuator_biasprm", &Model::actuator_biasprm)
      .property("actuator_actearly", &Model::actuator_actearly)
      .property("actuator_ctrlrange", &Model::actuator_ctrlrange)
      .property("actuator_forcerange", &Model::actuator_forcerange)
      .property("actuator_actrange", &Model::actuator_actrange)
      .property("actuator_gear", &Model::actuator_gear)
      .property("actuator_cranklength", &Model::actuator_cranklength)
      .property("actuator_acc0", &Model::actuator_acc0)
      .property("actuator_length0", &Model::actuator_length0)
      .property("actuator_lengthrange", &Model::actuator_lengthrange)
      .property("actuator_user", &Model::actuator_user)
      .property("actuator_plugin", &Model::actuator_plugin)

      // sensors
      .property("sensor_type", &Model::sensor_type)
      .property("sensor_datatype", &Model::sensor_datatype)
      .property("sensor_needstage", &Model::sensor_needstage)
      .property("sensor_objtype", &Model::sensor_objtype)
      .property("sensor_objid", &Model::sensor_objid)
      .property("sensor_reftype", &Model::sensor_reftype)
      .property("sensor_refid", &Model::sensor_refid)
      .property("sensor_dim", &Model::sensor_dim)
      .property("sensor_adr", &Model::sensor_adr)
      .property("sensor_cutoff", &Model::sensor_cutoff)
      .property("sensor_noise", &Model::sensor_noise)
      .property("sensor_user", &Model::sensor_user)
      .property("sensor_plugin", &Model::sensor_plugin)

      // plugin instances
      .property("plugin", &Model::plugin)
      .property("plugin_stateadr", &Model::plugin_stateadr)
      .property("plugin_statenum", &Model::plugin_statenum)
      .property("plugin_attr", &Model::plugin_attr)
      .property("plugin_attradr", &Model::plugin_attradr)

      // custom numeric fields
      .property("numeric_adr", &Model::numeric_adr)
      .property("numeric_size", &Model::numeric_size)
      .property("numeric_data", &Model::numeric_data)

      // custom text fields
      .property("text_adr", &Model::text_adr)
      .property("text_size", &Model::text_size)
      .property("text_data", &Model::text_data)

      // custom tuple fields
      .property("tuple_adr", &Model::tuple_adr)
      .property("tuple_size", &Model::tuple_size)
      .property("tuple_objtype", &Model::tuple_objtype)
      .property("tuple_objid", &Model::tuple_objid)
      .property("tuple_objprm", &Model::tuple_objprm)

      // keyframes
      .property("key_time", &Model::key_time)
      .property("key_qpos", &Model::key_qpos)
      .property("key_qvel", &Model::key_qvel)
      .property("key_act", &Model::key_act)
      .property("key_mpos", &Model::key_mpos)
      .property("key_mquat", &Model::key_mquat)
      .property("key_ctrl", &Model::key_ctrl)

      // names
      .property("name_bodyadr", &Model::name_bodyadr)
      .property("name_jntadr", &Model::name_jntadr)
      .property("name_geomadr", &Model::name_geomadr)
      .property("name_siteadr", &Model::name_siteadr)
      .property("name_camadr", &Model::name_camadr)
      .property("name_lightadr", &Model::name_lightadr)
      .property("name_flexadr", &Model::name_flexadr)
      .property("name_meshadr", &Model::name_meshadr)
      .property("name_skinadr", &Model::name_skinadr)
      .property("name_hfieldadr", &Model::name_hfieldadr)
      .property("name_texadr", &Model::name_texadr)
      .property("name_matadr", &Model::name_matadr)
      .property("name_pairadr", &Model::name_pairadr)
      .property("name_excludeadr", &Model::name_excludeadr)
      .property("name_eqadr", &Model::name_eqadr)
      .property("name_tendonadr", &Model::name_tendonadr)
      .property("name_actuatoradr", &Model::name_actuatoradr)
      .property("name_sensoradr", &Model::name_sensoradr)
      .property("name_numericadr", &Model::name_numericadr)
      .property("name_textadr", &Model::name_textadr)
      .property("name_tupleadr", &Model::name_tupleadr)
      .property("name_keyadr", &Model::name_keyadr)
      .property("name_pluginadr", &Model::name_pluginadr)
      .property("names", &Model::names)
      .property("names_map", &Model::names_map)

      // paths
      .property("paths", &Model::paths);

  class_<State>("State")
      .constructor<Model>()
      .function("ptr", &State::ptr, allow_raw_pointers())
      .function("free", &State::free)
      .function("getVal", &State::getVal);

  class_<Simulation>("Simulation")
      .constructor<Model *, State *>()
      .function("state", &Simulation::state, allow_raw_pointers())
      .function("model", &Simulation::model, allow_raw_pointers())
      .function("free", &Simulation::free)
      .function("applyForce", &Simulation::applyForce)
      .function("applyPose", &Simulation::applyPose)

      // MJDATA_BINDINGS
      .property("qpos", &Simulation::qpos)
      .property("qvel", &Simulation::qvel)
      .property("act", &Simulation::act)
      .property("qacc_warmstart", &Simulation::qacc_warmstart)
      .property("plugin_state", &Simulation::plugin_state)
      .property("ctrl", &Simulation::ctrl)
      .property("qfrc_applied", &Simulation::qfrc_applied)
      .property("xfrc_applied", &Simulation::xfrc_applied)
      .property("mocap_pos", &Simulation::mocap_pos)
      .property("mocap_quat", &Simulation::mocap_quat)
      .property("qacc", &Simulation::qacc)
      .property("act_dot", &Simulation::act_dot)
      .property("userdata", &Simulation::userdata)
      .property("sensordata", &Simulation::sensordata)
      .property("plugin", &Simulation::plugin)
      .property("plugin_data", &Simulation::plugin_data)
      .property("xpos", &Simulation::xpos)
      .property("xquat", &Simulation::xquat)
      .property("xmat", &Simulation::xmat)
      .property("xipos", &Simulation::xipos)
      .property("ximat", &Simulation::ximat)
      .property("xanchor", &Simulation::xanchor)
      .property("xaxis", &Simulation::xaxis)
      .property("geom_xpos", &Simulation::geom_xpos)
      .property("geom_xmat", &Simulation::geom_xmat)
      .property("site_xpos", &Simulation::site_xpos)
      .property("site_xmat", &Simulation::site_xmat)
      .property("cam_xpos", &Simulation::cam_xpos)
      .property("cam_xmat", &Simulation::cam_xmat)
      .property("light_xpos", &Simulation::light_xpos)
      .property("light_xdir", &Simulation::light_xdir)
      .property("subtree_com", &Simulation::subtree_com)
      .property("cdof", &Simulation::cdof)
      .property("cinert", &Simulation::cinert)
      .property("ten_wrapadr", &Simulation::ten_wrapadr)
      .property("ten_wrapnum", &Simulation::ten_wrapnum)
      .property("ten_J_rownnz", &Simulation::ten_J_rownnz)
      .property("ten_J_rowadr", &Simulation::ten_J_rowadr)
      .property("ten_J_colind", &Simulation::ten_J_colind)
      .property("ten_length", &Simulation::ten_length)
      .property("ten_J", &Simulation::ten_J)
      .property("wrap_obj", &Simulation::wrap_obj)
      .property("wrap_xpos", &Simulation::wrap_xpos)
      .property("actuator_length", &Simulation::actuator_length)
      .property("actuator_moment", &Simulation::actuator_moment)
      .property("crb", &Simulation::crb)
      .property("qM", &Simulation::qM)
      .property("qLD", &Simulation::qLD)
      .property("qLDiagInv", &Simulation::qLDiagInv)
      .property("qLDiagSqrtInv", &Simulation::qLDiagSqrtInv)
      .property("ten_velocity", &Simulation::ten_velocity)
      .property("actuator_velocity", &Simulation::actuator_velocity)
      .property("cvel", &Simulation::cvel)
      .property("cdof_dot", &Simulation::cdof_dot)
      .property("qfrc_bias", &Simulation::qfrc_bias)
      .property("qfrc_passive", &Simulation::qfrc_passive)
      .property("subtree_linvel", &Simulation::subtree_linvel)
      .property("subtree_angmom", &Simulation::subtree_angmom)
      .property("qH", &Simulation::qH)
      .property("qHDiagInv", &Simulation::qHDiagInv)
      .property("D_rownnz", &Simulation::D_rownnz)
      .property("D_rowadr", &Simulation::D_rowadr)
      .property("D_colind", &Simulation::D_colind)
      .property("qDeriv", &Simulation::qDeriv)
      .property("qLU", &Simulation::qLU)
      .property("actuator_force", &Simulation::actuator_force)
      .property("qfrc_actuator", &Simulation::qfrc_actuator)
      .property("qfrc_smooth", &Simulation::qfrc_smooth)
      .property("qacc_smooth", &Simulation::qacc_smooth)
      .property("qfrc_constraint", &Simulation::qfrc_constraint)
      .property("qfrc_inverse", &Simulation::qfrc_inverse)
      .property("cacc", &Simulation::cacc)
      .property("cfrc_int", &Simulation::cfrc_int)
      .property("cfrc_ext", &Simulation::cfrc_ext)

      // XML API
      .function("freeLastXML", &Simulation::freeLastXML)

      // Engine Forward API
      .function("step", &Simulation::step)
      .function("step1", &Simulation::step1)
      .function("step2", &Simulation::step2)
      .function("forward", &Simulation::forward)
      .function("forwardSkip", &Simulation::forwardSkip)
      .function("fwdPosition", &Simulation::fwdPosition)
      .function("fwdVelocity", &Simulation::fwdVelocity)
      .function("fwdActuation", &Simulation::fwdActuation)
      .function("fwdAcceleration", &Simulation::fwdAcceleration)
      .function("fwdConstraint", &Simulation::fwdConstraint)
      .function("Euler", &Simulation::Euler)
      .function("RungeKutta", &Simulation::RungeKutta)
      .function("checkPos", &Simulation::checkPos)
      .function("checkVel", &Simulation::checkVel)
      .function("checkAcc", &Simulation::checkAcc)

      // Engine Inverse API
      .function("inverse", &Simulation::inverse)
      .function("inverseSkip", &Simulation::inverseSkip)
      .function("invPosition", &Simulation::invPosition)
      .function("invVelocity", &Simulation::invVelocity)
      .function("invConstraint", &Simulation::invConstraint)
      .function("compareFwdInv", &Simulation::compareFwdInv)

      // Engine IO API
      .function("defaultSolRefImp", &Simulation::defaultSolRefImp,
                allow_raw_pointers())
      .function("sizeModel", &Simulation::sizeModel)
      .function("resetData", &Simulation::resetData)
      .function("resetDataDebug", &Simulation::resetDataDebug)
      .function("resetDataKeyframe", &Simulation::resetDataKeyframe)
      .function("deleteData", &Simulation::deleteData)

      // Engine Callback API
      .function("resetCallbacks", &Simulation::resetCallbacks)

      // Engine Print API
      .function("printFormattedModel", &Simulation::printFormattedModel)
      .function("printModel", &Simulation::printModel)
      .function("printFormattedData", &Simulation::printFormattedData)
      .function("printData", &Simulation::printData)

      // Engine Util API
      .function("printMat", &Simulation::printMat, allow_raw_pointers())

      // Engine Sensors API
      .function("sensorPos", &Simulation::sensorPos)
      .function("sensorVel", &Simulation::sensorVel)
      .function("sensorAcc", &Simulation::sensorAcc)
      .function("energyPos", &Simulation::energyPos)
      .function("energyVel", &Simulation::energyVel)

      // Engine Core Smooth API
      .function("kinematics", &Simulation::kinematics)
      .function("comPos", &Simulation::comPos)
      .function("camlight", &Simulation::camlight)
      .function("tendon", &Simulation::tendon)
      .function("transmission", &Simulation::transmission)
      .function("crbCalculate", &Simulation::crbCalculate)
      .function("factorM", &Simulation::factorM)
      .function("solveM", &Simulation::solveM, allow_raw_pointers())
      .function("solveM2", &Simulation::solveM2, allow_raw_pointers())
      .function("comVel", &Simulation::comVel)
      .function("subtreeVel", &Simulation::subtreeVel)
      .function("rne", &Simulation::rne, allow_raw_pointers())
      .function("rnePostConstraint", &Simulation::rnePostConstraint)

      // Engine Passive API
      .function("passive", &Simulation::passive)

      // Engine Collision Driver API
      .function("collision", &Simulation::collision)

      // Engine Core Contraints API
      .function("makeConstraint", &Simulation::makeConstraint)
      .function("projectConstraint", &Simulation::projectConstraint)
      .function("referenceConstraint", &Simulation::referenceConstraint)
      .function("isPyramidal", &Simulation::isPyramidal)
      .function("isSparse", &Simulation::isSparse)
      .function("isDual", &Simulation::isDual)
      .function("mulJacTVec", &Simulation::mulJacTVec, allow_raw_pointers())

      // Engine Support API
      .function("jacSubtreeCom", &Simulation::jacSubtreeCom,
                allow_raw_pointers())
      .function("differentiatePos", &Simulation::differentiatePos,
                allow_raw_pointers())
      .function("integratePos", &Simulation::integratePos, allow_raw_pointers())
      .function("normalizeQuat", &Simulation::normalizeQuat,
                allow_raw_pointers())
      .function("getTotalmass", &Simulation::getTotalmass)
      .function("fullM", &Simulation::fullM, allow_raw_pointers())
      .function("version", &Simulation::version)
      .function("versionString", &Simulation::versionString)

      // Engine Name API
      .function("name2id", &Simulation::name2id)
      .function("id2name", &Simulation::id2name)

      // Engine Plugin API
      .function("getPluginConfig", &Simulation::getPluginConfig)
      .function("loadPluginLibrary", &Simulation::loadPluginLibrary)

      // Render API
      .function("rectangle", &Simulation::rectangle)
      .function("finish", &Simulation::finish)
      .function("getError", &Simulation::getError)

      // UI API
      .function("themeSpacing", &Simulation::themeSpacing)
      .function("themeColor", &Simulation::themeColor)

      // Engine Error and Memory API
      .function("error", &Simulation::error)
      .function("error_i", &Simulation::error_i)
      .function("error_s", &Simulation::error_s)
      .function("warning", &Simulation::warning)
      .function("warning_i", &Simulation::warning_i)
      .function("warning_s", &Simulation::warning_s)
      .function("clearHandlers", &Simulation::clearHandlers)
      .function("writeLog", &Simulation::writeLog)

      // MuJoCo API
      .function("zero", &Simulation::zero, allow_raw_pointers())
      .function("fill", &Simulation::fill, allow_raw_pointers())
      .function("copy", &Simulation::copy, allow_raw_pointers())
      .function("sum", &Simulation::sum, allow_raw_pointers())
      .function("L1", &Simulation::L1, allow_raw_pointers())
      .function("scl", &Simulation::scl, allow_raw_pointers())
      .function("add", &Simulation::add, allow_raw_pointers())
      .function("sub", &Simulation::sub, allow_raw_pointers())
      .function("addTo", &Simulation::addTo, allow_raw_pointers())
      .function("subFrom", &Simulation::subFrom, allow_raw_pointers())
      .function("addToScl", &Simulation::addToScl, allow_raw_pointers())
      .function("addScl", &Simulation::addScl, allow_raw_pointers())
      .function("normalize", &Simulation::normalize, allow_raw_pointers())
      .function("norm", &Simulation::norm, allow_raw_pointers())
      .function("dot", &Simulation::dot, allow_raw_pointers())
      .function("mulMatVec", &Simulation::mulMatVec, allow_raw_pointers())
      .function("mulMatTVec", &Simulation::mulMatTVec, allow_raw_pointers())
      .function("mulVecMatVec", &Simulation::mulVecMatVec, allow_raw_pointers())
      .function("transpose", &Simulation::transpose, allow_raw_pointers())
      .function("symmetrize", &Simulation::symmetrize, allow_raw_pointers())
      .function("eye", &Simulation::eye, allow_raw_pointers())
      .function("mulMatMat", &Simulation::mulMatMat, allow_raw_pointers())
      .function("mulMatMatT", &Simulation::mulMatMatT, allow_raw_pointers())
      .function("mulMatTMat", &Simulation::mulMatTMat, allow_raw_pointers())
      .function("sqrMatTD", &Simulation::sqrMatTD, allow_raw_pointers())
      .function("cholFactor", &Simulation::cholFactor, allow_raw_pointers())
      .function("cholSolve", &Simulation::cholSolve, allow_raw_pointers())
      .function("cholUpdate", &Simulation::cholUpdate, allow_raw_pointers())
      .function("encodePyramid", &Simulation::encodePyramid,
                allow_raw_pointers())
      .function("decodePyramid", &Simulation::decodePyramid,
                allow_raw_pointers())
      .function("springDamper", &Simulation::springDamper)
      .function("min", &Simulation::min)
      .function("max", &Simulation::max)
      .function("clip", &Simulation::clip)
      .function("sign", &Simulation::sign)
      .function("round", &Simulation::round)
      .function("type2Str", &Simulation::type2Str)
      .function("str2Type", &Simulation::str2Type)
      .function("writeNumBytes", &Simulation::writeNumBytes)
      .function("warningText", &Simulation::warningText)
      .function("isBad", &Simulation::isBad)
      .function("isZero", &Simulation::isZero, allow_raw_pointers())
      .function("standardNormal", &Simulation::standardNormal,
                allow_raw_pointers())
      .function("insertionSort", &Simulation::insertionSort,
                allow_raw_pointers())
      .function("Halton", &Simulation::Halton)
      .function("sigmoid", &Simulation::sigmoid)
      .function("transitionFD", &Simulation::transitionFD, allow_raw_pointers())
      .function("pluginCount", &Simulation::pluginCount);

  value_object<mjModel>("mjModel")
      .field("ngeom", &mjModel::ngeom)
      .field("nq", &mjModel::nq)
      .field("na", &mjModel::na)
      .field("nv", &mjModel::nv)
      .field("nu", &mjModel::nu)
      .field("nbody", &mjModel::nbody)
      .field("nsensordata", &mjModel::nsensordata)
      .field("nmesh", &mjModel::nmesh)
      .field("nmeshvert", &mjModel::nmeshvert)
      .field("nmeshface", &mjModel::nmeshface);

  value_object<mjvPerturb>("mjvPerturb")
      .field("select", &mjvPerturb::select)
      .field("skinselect", &mjvPerturb::skinselect)
      .field("active", &mjvPerturb::active)
      .field("active2", &mjvPerturb::active2)
      .field("refpos", &mjvPerturb::refpos)
      .field("refquat", &mjvPerturb::refquat)
      .field("localpos", &mjvPerturb::localpos)
      .field("scale", &mjvPerturb::scale);

  value_object<mjContact>("mjContact")
      .field("dist", &mjContact::dist)
      .field("pos", &mjContact::pos)
      .field("frame", &mjContact::frame)
      .field("includemargin", &mjContact::includemargin)
      .field("friction", &mjContact::friction)
      .field("solref", &mjContact::solref)
      .field("solimp", &mjContact::solimp)
      .field("mu", &mjContact::mu)
      .field("H", &mjContact::H)
      .field("dim", &mjContact::H)
      .field("geom1", &mjContact::H)
      .field("geom2", &mjContact::H)
      .field("exclude", &mjContact::exclude)
      .field("efc_address", &mjContact::efc_address);

  register_vector<mjContact>("vector<mjContact>");
}